[package]
name = "purpledot"
version = "0.1.0"
edition = "2018"

[dependencies]
image = "0.24.6"
ffimage = "0.9.0"
rsmpeg = "0.14.1+ffmpeg.6.0"
color-eyre = "0.6.2"

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev.package.rsmpeg]
opt-level = 3